# Generated by Django 3.2.3 on 2021-05-21 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_lev1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='lev1',
            new_name='Level1',
        ),
    ]
