# Generated by Django 3.2.3 on 2021-05-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_lev1_level1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level1',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='level1_pics'),
        ),
    ]
